name: 'Boggle Group 10'

on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build /p:Configuration=Release BoggleAPI/BoggleAPI.sln
      - name: Run Unit Tests
        run: dotnet test ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./BoggleAPI/BoggleAPITest/bin/Release/Tests.dll